/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiDemoRouteImport } from './routes/api/demo'
import { Route as publicUnsubscribedRouteImport } from './routes/(public)/unsubscribed'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicChangelogRouteImport } from './routes/(public)/changelog'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appLayoutImportRouteImport } from './routes/(app)/_layout/import'
import { Route as appLayoutDashboardRouteImport } from './routes/(app)/_layout/dashboard'
import { Route as appLayoutTradesIndexRouteImport } from './routes/(app)/_layout/trades/index'
import { Route as appLayoutSettingsIndexRouteImport } from './routes/(app)/_layout/settings/index'
import { Route as appLayoutPlansIndexRouteImport } from './routes/(app)/_layout/plans/index'
import { Route as appLayoutDigestIndexRouteImport } from './routes/(app)/_layout/digest/index'
import { Route as appLayoutDetectorsIndexRouteImport } from './routes/(app)/_layout/detectors/index'
import { Route as appLayoutTradesPositionIdRouteImport } from './routes/(app)/_layout/trades/$positionId'
import { Route as appLayoutPlansNewRouteImport } from './routes/(app)/_layout/plans/new'
import { Route as appLayoutPlansPlanIdRouteImport } from './routes/(app)/_layout/plans/$planId'
import { Route as appLayoutDetectorsNewRouteImport } from './routes/(app)/_layout/detectors/new'
import { Route as appLayoutDetectorsDetectorIdRouteImport } from './routes/(app)/_layout/detectors/$detectorId'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const publicUnsubscribedRoute = publicUnsubscribedRouteImport.update({
  id: '/(public)/unsubscribed',
  path: '/unsubscribed',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicChangelogRoute = publicChangelogRouteImport.update({
  id: '/(public)/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutImportRoute = appLayoutImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutDashboardRoute = appLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutTradesIndexRoute = appLayoutTradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutSettingsIndexRoute = appLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutPlansIndexRoute = appLayoutPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutDigestIndexRoute = appLayoutDigestIndexRouteImport.update({
  id: '/digest/',
  path: '/digest/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutDetectorsIndexRoute = appLayoutDetectorsIndexRouteImport.update({
  id: '/detectors/',
  path: '/detectors/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutTradesPositionIdRoute =
  appLayoutTradesPositionIdRouteImport.update({
    id: '/trades/$positionId',
    path: '/trades/$positionId',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutPlansNewRoute = appLayoutPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutPlansPlanIdRoute = appLayoutPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutDetectorsNewRoute = appLayoutDetectorsNewRouteImport.update({
  id: '/detectors/new',
  path: '/detectors/new',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutDetectorsDetectorIdRoute =
  appLayoutDetectorsDetectorIdRouteImport.update({
    id: '/detectors/$detectorId',
    path: '/detectors/$detectorId',
    getParentRoute: () => appLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/changelog': typeof publicChangelogRoute
  '/login': typeof publicLoginRoute
  '/unsubscribed': typeof publicUnsubscribedRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/import': typeof appLayoutImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/detectors/$detectorId': typeof appLayoutDetectorsDetectorIdRoute
  '/detectors/new': typeof appLayoutDetectorsNewRoute
  '/plans/$planId': typeof appLayoutPlansPlanIdRoute
  '/plans/new': typeof appLayoutPlansNewRoute
  '/trades/$positionId': typeof appLayoutTradesPositionIdRoute
  '/detectors/': typeof appLayoutDetectorsIndexRoute
  '/digest/': typeof appLayoutDigestIndexRoute
  '/plans/': typeof appLayoutPlansIndexRoute
  '/settings/': typeof appLayoutSettingsIndexRoute
  '/trades/': typeof appLayoutTradesIndexRoute
}
export interface FileRoutesByTo {
  '/changelog': typeof publicChangelogRoute
  '/login': typeof publicLoginRoute
  '/unsubscribed': typeof publicUnsubscribedRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/': typeof publicIndexRoute
  '/dashboard': typeof appLayoutDashboardRoute
  '/import': typeof appLayoutImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/detectors/$detectorId': typeof appLayoutDetectorsDetectorIdRoute
  '/detectors/new': typeof appLayoutDetectorsNewRoute
  '/plans/$planId': typeof appLayoutPlansPlanIdRoute
  '/plans/new': typeof appLayoutPlansNewRoute
  '/trades/$positionId': typeof appLayoutTradesPositionIdRoute
  '/detectors': typeof appLayoutDetectorsIndexRoute
  '/digest': typeof appLayoutDigestIndexRoute
  '/plans': typeof appLayoutPlansIndexRoute
  '/settings': typeof appLayoutSettingsIndexRoute
  '/trades': typeof appLayoutTradesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(public)/changelog': typeof publicChangelogRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/unsubscribed': typeof publicUnsubscribedRoute
  '/api/demo': typeof ApiDemoRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/(public)/': typeof publicIndexRoute
  '/(app)/_layout/dashboard': typeof appLayoutDashboardRoute
  '/(app)/_layout/import': typeof appLayoutImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/_layout/detectors/$detectorId': typeof appLayoutDetectorsDetectorIdRoute
  '/(app)/_layout/detectors/new': typeof appLayoutDetectorsNewRoute
  '/(app)/_layout/plans/$planId': typeof appLayoutPlansPlanIdRoute
  '/(app)/_layout/plans/new': typeof appLayoutPlansNewRoute
  '/(app)/_layout/trades/$positionId': typeof appLayoutTradesPositionIdRoute
  '/(app)/_layout/detectors/': typeof appLayoutDetectorsIndexRoute
  '/(app)/_layout/digest/': typeof appLayoutDigestIndexRoute
  '/(app)/_layout/plans/': typeof appLayoutPlansIndexRoute
  '/(app)/_layout/settings/': typeof appLayoutSettingsIndexRoute
  '/(app)/_layout/trades/': typeof appLayoutTradesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/changelog'
    | '/login'
    | '/unsubscribed'
    | '/api/demo'
    | '/api/inngest'
    | '/api/unsubscribe'
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/auth/$'
    | '/detectors/$detectorId'
    | '/detectors/new'
    | '/plans/$planId'
    | '/plans/new'
    | '/trades/$positionId'
    | '/detectors/'
    | '/digest/'
    | '/plans/'
    | '/settings/'
    | '/trades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/changelog'
    | '/login'
    | '/unsubscribed'
    | '/api/demo'
    | '/api/inngest'
    | '/api/unsubscribe'
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/auth/$'
    | '/detectors/$detectorId'
    | '/detectors/new'
    | '/plans/$planId'
    | '/plans/new'
    | '/trades/$positionId'
    | '/detectors'
    | '/digest'
    | '/plans'
    | '/settings'
    | '/trades'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/(public)/changelog'
    | '/(public)/login'
    | '/(public)/unsubscribed'
    | '/api/demo'
    | '/api/inngest'
    | '/api/unsubscribe'
    | '/(public)/'
    | '/(app)/_layout/dashboard'
    | '/(app)/_layout/import'
    | '/api/auth/$'
    | '/(app)/_layout/detectors/$detectorId'
    | '/(app)/_layout/detectors/new'
    | '/(app)/_layout/plans/$planId'
    | '/(app)/_layout/plans/new'
    | '/(app)/_layout/trades/$positionId'
    | '/(app)/_layout/detectors/'
    | '/(app)/_layout/digest/'
    | '/(app)/_layout/plans/'
    | '/(app)/_layout/settings/'
    | '/(app)/_layout/trades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
  publicChangelogRoute: typeof publicChangelogRoute
  publicLoginRoute: typeof publicLoginRoute
  publicUnsubscribedRoute: typeof publicUnsubscribedRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  publicIndexRoute: typeof publicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/unsubscribed': {
      id: '/(public)/unsubscribed'
      path: '/unsubscribed'
      fullPath: '/unsubscribed'
      preLoaderRoute: typeof publicUnsubscribedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/changelog': {
      id: '/(public)/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof publicChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/import': {
      id: '/(app)/_layout/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof appLayoutImportRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/dashboard': {
      id: '/(app)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appLayoutDashboardRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/trades/': {
      id: '/(app)/_layout/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof appLayoutTradesIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/settings/': {
      id: '/(app)/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appLayoutSettingsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/plans/': {
      id: '/(app)/_layout/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof appLayoutPlansIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/digest/': {
      id: '/(app)/_layout/digest/'
      path: '/digest'
      fullPath: '/digest/'
      preLoaderRoute: typeof appLayoutDigestIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/detectors/': {
      id: '/(app)/_layout/detectors/'
      path: '/detectors'
      fullPath: '/detectors/'
      preLoaderRoute: typeof appLayoutDetectorsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/trades/$positionId': {
      id: '/(app)/_layout/trades/$positionId'
      path: '/trades/$positionId'
      fullPath: '/trades/$positionId'
      preLoaderRoute: typeof appLayoutTradesPositionIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/plans/new': {
      id: '/(app)/_layout/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof appLayoutPlansNewRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/plans/$planId': {
      id: '/(app)/_layout/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof appLayoutPlansPlanIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/detectors/new': {
      id: '/(app)/_layout/detectors/new'
      path: '/detectors/new'
      fullPath: '/detectors/new'
      preLoaderRoute: typeof appLayoutDetectorsNewRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/detectors/$detectorId': {
      id: '/(app)/_layout/detectors/$detectorId'
      path: '/detectors/$detectorId'
      fullPath: '/detectors/$detectorId'
      preLoaderRoute: typeof appLayoutDetectorsDetectorIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
  }
}

interface appLayoutRouteChildren {
  appLayoutDashboardRoute: typeof appLayoutDashboardRoute
  appLayoutImportRoute: typeof appLayoutImportRoute
  appLayoutDetectorsDetectorIdRoute: typeof appLayoutDetectorsDetectorIdRoute
  appLayoutDetectorsNewRoute: typeof appLayoutDetectorsNewRoute
  appLayoutPlansPlanIdRoute: typeof appLayoutPlansPlanIdRoute
  appLayoutPlansNewRoute: typeof appLayoutPlansNewRoute
  appLayoutTradesPositionIdRoute: typeof appLayoutTradesPositionIdRoute
  appLayoutDetectorsIndexRoute: typeof appLayoutDetectorsIndexRoute
  appLayoutDigestIndexRoute: typeof appLayoutDigestIndexRoute
  appLayoutPlansIndexRoute: typeof appLayoutPlansIndexRoute
  appLayoutSettingsIndexRoute: typeof appLayoutSettingsIndexRoute
  appLayoutTradesIndexRoute: typeof appLayoutTradesIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutDashboardRoute: appLayoutDashboardRoute,
  appLayoutImportRoute: appLayoutImportRoute,
  appLayoutDetectorsDetectorIdRoute: appLayoutDetectorsDetectorIdRoute,
  appLayoutDetectorsNewRoute: appLayoutDetectorsNewRoute,
  appLayoutPlansPlanIdRoute: appLayoutPlansPlanIdRoute,
  appLayoutPlansNewRoute: appLayoutPlansNewRoute,
  appLayoutTradesPositionIdRoute: appLayoutTradesPositionIdRoute,
  appLayoutDetectorsIndexRoute: appLayoutDetectorsIndexRoute,
  appLayoutDigestIndexRoute: appLayoutDigestIndexRoute,
  appLayoutPlansIndexRoute: appLayoutPlansIndexRoute,
  appLayoutSettingsIndexRoute: appLayoutSettingsIndexRoute,
  appLayoutTradesIndexRoute: appLayoutTradesIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
  publicChangelogRoute: publicChangelogRoute,
  publicLoginRoute: publicLoginRoute,
  publicUnsubscribedRoute: publicUnsubscribedRoute,
  ApiDemoRoute: ApiDemoRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  publicIndexRoute: publicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
