/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appImportRouteImport } from './routes/(app)/import'
import { Route as appLayoutRouteImport } from './routes/(app)/_layout'
import { Route as appTradesIndexRouteImport } from './routes/(app)/trades/index'
import { Route as appDigestIndexRouteImport } from './routes/(app)/digest/index'

const appTradesIndexRoute = appTradesIndexRouteImport.update({
  id: '/(app)/trades/',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const appDigestIndexRoute = appDigestIndexRouteImport.update({
  id: '/(app)/digest/',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appImportRoute = appImportRouteImport.update({
  id: '/(app)/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof appDashboardRoute
  '/import': typeof appImportRoute
  '/trades': typeof appTradesIndexRoute
  '/digest': typeof appDigestIndexRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof appDashboardRoute
  '/import': typeof appImportRoute
  '/trades': typeof appTradesIndexRoute
  '/digest': typeof appDigestIndexRoute
  '/login': typeof publicLoginRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_layout': typeof appLayoutRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/import': typeof appImportRoute
  '/(app)/trades/': typeof appTradesIndexRoute
  '/(app)/digest/': typeof appDigestIndexRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/': typeof publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/import' | '/trades' | '/digest' | '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/import' | '/trades' | '/digest' | '/login' | '/'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/(app)/dashboard'
    | '/(app)/import'
    | '/(app)/trades/'
    | '/(app)/digest/'
    | '/(public)/login'
    | '/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRoute
  appDashboardRoute: typeof appDashboardRoute
  appImportRoute: typeof appImportRoute
  appTradesIndexRoute: typeof appTradesIndexRoute
  appDigestIndexRoute: typeof appDigestIndexRoute
  publicLoginRoute: typeof publicLoginRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/import': {
      id: '/(app)/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof appImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/trades/': {
      id: '/(app)/trades/'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof appTradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/digest/': {
      id: '/(app)/digest/'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof appDigestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRoute,
  appDashboardRoute: appDashboardRoute,
  appImportRoute: appImportRoute,
  appTradesIndexRoute: appTradesIndexRoute,
  appDigestIndexRoute: appDigestIndexRoute,
  publicLoginRoute: publicLoginRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
